name: measure_performance
description: Measure various performance metrics like memory usage and duration elapsed of an operation
version: 1.1.0
repository: https://github.com/predatorx7/dart_measure_performance
topics:
  - performance
  - monitoring
  - insights

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
